# Generated by Django 3.1.1 on 2020-09-24 10:51

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=200)),
                ('previous_efforts', models.TextField()),
                ('next_efforts', models.TextField()),
                ('impediments', models.TextField()),
                ('other_notable_feedback', models.CharField(max_length=200)),
                ('to_time', django_jalali.db.models.jDateTimeField()),
            ],
        ),
    ]
