# Generated by Django 3.1.1 on 2020-09-24 10:53

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='from_time',
            field=django_jalali.db.models.jDateTimeField(default='1399-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='other_notable_feedback',
            field=models.TextField(),
        ),
    ]
