# Generated by Django 3.1.1 on 2020-09-28 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_activity', '0004_auto_20200927_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_project', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='eventlog',
            old_name='datetime_submitted',
            new_name='datetime_occured',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='impediments',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='next_efforts',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='other_notable_feedback',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='previous_efforts',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='to_time',
        ),
        migrations.CreateModel(
            name='WorkUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('Work Started', 'کار شروع شد'), ('Work Paused', 'کار متوقف شد'), ('Work Stuck', 'کار با مانع رو به رو شد'), ('Work Advanced', ' کار در حال پیشروی است'), ('Work Succeeded', 'کار با موفقیت پایان یافت'), ('Work Canceled', 'کار لغو شد'), ('Work Failed', 'کار با شکست مواجه شد')], max_length=20)),
                ('work_title', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('estimated_remaining_time', models.DurationField()),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_activity.activity')),
            ],
        ),
    ]
