# Generated by Django 3.1.1 on 2020-09-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_activity', '0005_auto_20200928_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='event_message',
            field=models.TextField(default='blah blah blah'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(default='Work Started', max_length=40),
            preserve_default=False,
        ),
    ]
