# Generated by Django 3.1.1 on 2020-09-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_activity', '0009_auto_20200929_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'فعالیت', 'verbose_name_plural': 'فعالیت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'سابقه\u200cی حضور و غیاب', 'verbose_name_plural': 'سوابق حضور و غیاب'},
        ),
        migrations.AlterModelOptions(
            name='availabilitystatus',
            options={'verbose_name': 'وضعیت کارمند', 'verbose_name_plural': 'وضعیت\u200cهای کارمند'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'کارمند', 'verbose_name_plural': 'کارمندان'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'لاگ', 'verbose_name_plural': 'لاگ\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'verbose_name': 'محل کار', 'verbose_name_plural': 'محل\u200cهای کار'},
        ),
        migrations.AlterModelOptions(
            name='workupdate',
            options={'verbose_name': 'اعلان کاری', 'verbose_name_plural': 'اعلانات کاری'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Sales', 'فروش'), ('Marketing', 'بازاریابی'), ('Project Management', 'مدیریت پروژه'), ('Operations', 'عملیات'), ('Human Resources', 'امور منابع انسانی'), ('Support', 'پشتیبانی'), ('Research and Development', 'تحقیق و توسعه'), ('Learning and Development', 'آموزش و توسعه'), ('Product Management', 'مدیریت محصول'), ('Finance', 'امور مالی'), ('Software Development', 'توسعه\u200cی نرم\u200cافزار'), ('Design', 'طراحی'), ('Search Engine Optimization', 'بهینه\u200cسازی موتور جستجو'), ('Contracts', 'امور قراردادها'), ('General', 'عمومی')], default='Standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='workupdate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
