# Generated by Django 3.1.1 on 2020-10-08 21:19

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_activity', '0010_auto_20200929_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='datetime_occured',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availabilitystatus',
            name='datetime_occured',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workupdate',
            name='datetime_occured',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
