# Generated by Django 3.1.1 on 2020-10-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_activity', '0011_auto_20201008_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='آرشیو شده؟'),
        ),
    ]
