# Generated by Django 3.1.1 on 2020-11-05 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_activity', '0012_activity_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_present_now',
            field=models.BooleanField(default=False, verbose_name='الان در سازمان حضور دارد؟'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Sales', 'فروش'), ('Marketing', 'بازاریابی'), ('Project Management', 'مدیریت پروژه'), ('Operations', 'عملیات'), ('Human Resources', 'امور منابع انسانی'), ('Support', 'پشتیبانی'), ('Research and Development', 'تحقیق و توسعه'), ('Learning and Development', 'آموزش و توسعه'), ('Product Management', 'مدیریت محصول'), ('Finance', 'امور مالی'), ('Software Development', 'توسعه\u200cی نرم\u200cافزار'), ('Design', 'طراحی'), ('Search Engine Optimization', 'بهینه\u200cسازی موتور جستجو'), ('Contracts', 'امور قراردادها'), ('General', 'عمومی')], default='Standard', max_length=50, verbose_name='نوع فعالیت'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=50, verbose_name='موضوع فعالیت'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='action_type',
            field=models.CharField(choices=[('Enter', 'ورود'), ('Exit', 'خروج')], max_length=10, verbose_name='نوع فعالیت'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='datetime_occured',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_activity.employee', verbose_name='کارمند'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_activity.log', verbose_name='لاگ مربوطه'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_activity.workplace', verbose_name='محل کار'),
        ),
        migrations.AlterField(
            model_name='availabilitystatus',
            name='datetime_occured',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='availabilitystatus',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_activity.employee', verbose_name='کارمند'),
        ),
        migrations.AlterField(
            model_name='availabilitystatus',
            name='log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_activity.log', verbose_name='لاگ مربوطه'),
        ),
        migrations.AlterField(
            model_name='availabilitystatus',
            name='reason',
            field=models.CharField(choices=[('Available', 'در دسترس'), ('In a Meeting', 'در جلسه'), ('Focusing', 'در حال تمرکز'), ('Busy', 'مشغول'), ('On Hourly Leave', 'در مرخصی ساعتی'), ('On Daily Leave', 'در مرخصی روزانه'), ('Left Work', 'سازمان را ترک کرده'), ('Away', 'ترک میز'), ('Away for a meal', 'ترک میز برای صرف وعده\u200cی غذایی')], max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='availabilitystatus',
            name='until',
            field=django_jalali.db.models.jDateTimeField(verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(max_length=100, verbose_name='عنوان شغل'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='log',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_activity.employee', verbose_name='کارمند'),
        ),
        migrations.AlterField(
            model_name='log',
            name='event_message',
            field=models.TextField(verbose_name='موضوع لاگ'),
        ),
        migrations.AlterField(
            model_name='log',
            name='event_type',
            field=models.CharField(max_length=40, verbose_name='نوع لاگ'),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='name',
            field=models.CharField(max_length=40, verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='workupdate',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_activity.activity', verbose_name='فعالیت'),
        ),
        migrations.AlterField(
            model_name='workupdate',
            name='datetime_occured',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='workupdate',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_activity.employee', verbose_name='کارمند'),
        ),
        migrations.AlterField(
            model_name='workupdate',
            name='estimated_remaining_time',
            field=models.DurationField(verbose_name='زمان تقریبی باقی مانده'),
        ),
        migrations.AlterField(
            model_name='workupdate',
            name='log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_activity.log', verbose_name='لاگ مربوطه'),
        ),
        migrations.AlterField(
            model_name='workupdate',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='workupdate',
            name='update_type',
            field=models.CharField(choices=[('Work Started', 'کار شروع شد'), ('Work Paused', 'کار متوقف شد'), ('Work Stuck', 'کار با مانع رو به رو شد'), ('Work Advanced', ' کار در حال پیشروی است'), ('Work Succeeded', 'کار با موفقیت پایان یافت'), ('Work Canceled', 'کار لغو شد'), ('Work Failed', 'کار با شکست مواجه شد')], max_length=20, verbose_name='نوع اعلان'),
        ),
        migrations.AlterField(
            model_name='workupdate',
            name='work_title',
            field=models.CharField(max_length=200, verbose_name='عنوان کار'),
        ),
    ]
